---

- name: Demo Git Module
  hosts: all
  tasks:

    - name: Clone a repo
      ansible.builtin.git:
        repo: https://github.com/Kiefferflo/GithubAction.git
        dest: /home/cytech/sandbox/clone
        clone: yes
        update: yes
        
- name: Deploying repo Content
  hosts: all
  tasks:
    - name : Installing angular
      ansible.builtin.shell:
        chdir: /home/cytech/sandbox/clone/
        cmd: npm install -g @angular/cli@14.2.5
    - name : Installing nmp
      ansible.builtin.shell:
        chdir: /home/cytech/sandbox/clone/
        cmd: npm install
    - name : Deploying
      ansible.builtin.shell:
        chdir: /home/cytech/sandbox/clone/
        cmd: ng build
